"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from app import is_csv_file
import os

APP = ["app.py"]

DATA_FILES = [os.path.join("data", f) for f in os.listdir("data") if is_csv_file(f)] + \
        ["assets"]

OPTIONS = {
    'iconfile': "assets/backprop_playground.png",
}

setup(
    name="BPPG",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
