"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["app.py"]

DATA_FILES = ["assets", "data"]

OPTIONS = {
    'iconfile': "assets/backprop_playground.png",
}

setup(
    name="BPPG",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
